window.COURSES = [
  {
    "id": "材料力學-1",
    "subject": "材料力學",
    "name": "第01-1堂",
    "duration": "02:42:28",
    "seconds": 9748,
    "pageStart": "",
    "pageEnd": "",
    "order": 1,
    "color": "#c96d55"
  },
  {
    "id": "材料力學-2",
    "subject": "材料力學",
    "name": "第01-2堂",
    "duration": "00:41:51",
    "seconds": 2511,
    "pageStart": "",
    "pageEnd": "",
    "order": 2,
    "color": "#c96d55"
  },
  {
    "id": "材料力學-3",
    "subject": "材料力學",
    "name": "第02-1堂",
    "duration": "02:10:18",
    "seconds": 7818,
    "pageStart": "",
    "pageEnd": "",
    "order": 3,
    "color": "#c96d55"
  },
  {
    "id": "材料力學-4",
    "subject": "材料力學",
    "name": "第02-2堂",
    "duration": "01:10:40",
    "seconds": 4240,
    "pageStart": "",
    "pageEnd": "",
    "order": 4,
    "color": "#c96d55"
  },
  {
    "id": "材料力學-5",
    "subject": "材料力學",
    "name": "第03-1堂",
    "duration": "02:05:56",
    "seconds": 7556,
    "pageStart": "",
    "pageEnd": "",
    "order": 5,
    "color": "#c96d55"
  },
  {
    "id": "材料力學-6",
    "subject": "材料力學",
    "name": "第03-2堂",
    "duration": "01:07:04",
    "seconds": 4024,
    "pageStart": "",
    "pageEnd": "",
    "order": 6,
    "color": "#c96d55"
  },
  {
    "id": "材料力學-7",
    "subject": "材料力學",
    "name": "第04-1堂",
    "duration": "02:10:56",
    "seconds": 7856,
    "pageStart": "",
    "pageEnd": "",
    "order": 7,
    "color": "#c96d55"
  },
  {
    "id": "材料力學-8",
    "subject": "材料力學",
    "name": "第04-2堂",
    "duration": "01:10:58",
    "seconds": 4258,
    "pageStart": "",
    "pageEnd": "",
    "order": 8,
    "color": "#c96d55"
  },
  {
    "id": "材料力學-9",
    "subject": "材料力學",
    "name": "第05-1堂",
    "duration": "02:33:07",
    "seconds": 9187,
    "pageStart": "",
    "pageEnd": "",
    "order": 9,
    "color": "#c96d55"
  },
  {
    "id": "材料力學-10",
    "subject": "材料力學",
    "name": "第05-2堂",
    "duration": "00:51:51",
    "seconds": 3111,
    "pageStart": "",
    "pageEnd": "",
    "order": 10,
    "color": "#c96d55"
  },
  {
    "id": "材料力學-11",
    "subject": "材料力學",
    "name": "第06-1堂",
    "duration": "02:30:16",
    "seconds": 9016,
    "pageStart": "",
    "pageEnd": "",
    "order": 11,
    "color": "#c96d55"
  },
  {
    "id": "材料力學-12",
    "subject": "材料力學",
    "name": "第06-2堂",
    "duration": "00:52:32",
    "seconds": 3152,
    "pageStart": "",
    "pageEnd": "",
    "order": 12,
    "color": "#c96d55"
  },
  {
    "id": "材料力學-13",
    "subject": "材料力學",
    "name": "第07-1堂",
    "duration": "02:22:39",
    "seconds": 8559,
    "pageStart": "",
    "pageEnd": "",
    "order": 13,
    "color": "#c96d55"
  },
  {
    "id": "材料力學-14",
    "subject": "材料力學",
    "name": "第07-2堂",
    "duration": "01:04:44",
    "seconds": 3884,
    "pageStart": "",
    "pageEnd": "",
    "order": 14,
    "color": "#c96d55"
  },
  {
    "id": "材料力學-15",
    "subject": "材料力學",
    "name": "第08-1堂",
    "duration": "02:29:28",
    "seconds": 8968,
    "pageStart": "",
    "pageEnd": "",
    "order": 15,
    "color": "#c96d55"
  },
  {
    "id": "材料力學-16",
    "subject": "材料力學",
    "name": "第08-2堂",
    "duration": "00:37:21",
    "seconds": 2241,
    "pageStart": "",
    "pageEnd": "",
    "order": 16,
    "color": "#c96d55"
  },
  {
    "id": "材料力學-17",
    "subject": "材料力學",
    "name": "第09-1堂",
    "duration": "02:33:07",
    "seconds": 9187,
    "pageStart": "",
    "pageEnd": "",
    "order": 17,
    "color": "#c96d55"
  },
  {
    "id": "材料力學-18",
    "subject": "材料力學",
    "name": "第09-2堂",
    "duration": "00:52:29",
    "seconds": 3149,
    "pageStart": "",
    "pageEnd": "",
    "order": 18,
    "color": "#c96d55"
  },
  {
    "id": "材料力學-19",
    "subject": "材料力學",
    "name": "第10-1堂",
    "duration": "02:43:55",
    "seconds": 9835,
    "pageStart": "",
    "pageEnd": "",
    "order": 19,
    "color": "#c96d55"
  },
  {
    "id": "材料力學-20",
    "subject": "材料力學",
    "name": "第10-2堂",
    "duration": "00:39:45",
    "seconds": 2385,
    "pageStart": "",
    "pageEnd": "",
    "order": 20,
    "color": "#c96d55"
  },
  {
    "id": "微積分-1",
    "subject": "微積分",
    "name": "第01-1堂",
    "duration": "01:24:54",
    "seconds": 5094,
    "pageStart": "",
    "pageEnd": "",
    "order": 1,
    "color": "#4f7cff"
  },
  {
    "id": "微積分-2",
    "subject": "微積分",
    "name": "第01-2堂",
    "duration": "01:02:33",
    "seconds": 3753,
    "pageStart": "",
    "pageEnd": "",
    "order": 2,
    "color": "#4f7cff"
  },
  {
    "id": "微積分-3",
    "subject": "微積分",
    "name": "第02-1堂",
    "duration": "01:32:24",
    "seconds": 5544,
    "pageStart": "",
    "pageEnd": "",
    "order": 3,
    "color": "#4f7cff"
  },
  {
    "id": "微積分-4",
    "subject": "微積分",
    "name": "第02-2堂",
    "duration": "01:01:21",
    "seconds": 3681,
    "pageStart": "",
    "pageEnd": "",
    "order": 4,
    "color": "#4f7cff"
  },
  {
    "id": "微積分-5",
    "subject": "微積分",
    "name": "第03-1堂",
    "duration": "01:31:17",
    "seconds": 5477,
    "pageStart": "",
    "pageEnd": "",
    "order": 5,
    "color": "#4f7cff"
  },
  {
    "id": "微積分-6",
    "subject": "微積分",
    "name": "第03-2堂",
    "duration": "01:01:47",
    "seconds": 3707,
    "pageStart": "",
    "pageEnd": "",
    "order": 6,
    "color": "#4f7cff"
  },
  {
    "id": "微積分-7",
    "subject": "微積分",
    "name": "第04-1堂",
    "duration": "01:29:14",
    "seconds": 5354,
    "pageStart": "",
    "pageEnd": "",
    "order": 7,
    "color": "#4f7cff"
  },
  {
    "id": "微積分-8",
    "subject": "微積分",
    "name": "第04-2堂",
    "duration": "01:03:00",
    "seconds": 3780,
    "pageStart": "",
    "pageEnd": "",
    "order": 8,
    "color": "#4f7cff"
  },
  {
    "id": "微積分-9",
    "subject": "微積分",
    "name": "第05-1堂",
    "duration": "01:29:25",
    "seconds": 5365,
    "pageStart": "",
    "pageEnd": "",
    "order": 9,
    "color": "#4f7cff"
  },
  {
    "id": "微積分-10",
    "subject": "微積分",
    "name": "第05-2堂",
    "duration": "00:55:43",
    "seconds": 3343,
    "pageStart": "",
    "pageEnd": "",
    "order": 10,
    "color": "#4f7cff"
  },
  {
    "id": "微積分-11",
    "subject": "微積分",
    "name": "第06-1堂",
    "duration": "01:27:46",
    "seconds": 5266,
    "pageStart": "",
    "pageEnd": "",
    "order": 11,
    "color": "#4f7cff"
  },
  {
    "id": "微積分-12",
    "subject": "微積分",
    "name": "第06-2堂",
    "duration": "00:59:48",
    "seconds": 3588,
    "pageStart": "",
    "pageEnd": "",
    "order": 12,
    "color": "#4f7cff"
  },
  {
    "id": "微積分-13",
    "subject": "微積分",
    "name": "第07-1堂",
    "duration": "01:32:22",
    "seconds": 5542,
    "pageStart": "",
    "pageEnd": "",
    "order": 13,
    "color": "#4f7cff"
  },
  {
    "id": "微積分-14",
    "subject": "微積分",
    "name": "第07-2堂",
    "duration": "01:01:25",
    "seconds": 3685,
    "pageStart": "",
    "pageEnd": "",
    "order": 14,
    "color": "#4f7cff"
  },
  {
    "id": "微積分-15",
    "subject": "微積分",
    "name": "第08-1堂",
    "duration": "01:28:55",
    "seconds": 5335,
    "pageStart": "",
    "pageEnd": "",
    "order": 15,
    "color": "#4f7cff"
  },
  {
    "id": "微積分-16",
    "subject": "微積分",
    "name": "第08-2堂",
    "duration": "01:02:56",
    "seconds": 3776,
    "pageStart": "",
    "pageEnd": "",
    "order": 16,
    "color": "#4f7cff"
  },
  {
    "id": "工程數學-1",
    "subject": "工程數學",
    "name": "第01-1堂",
    "duration": "01:17:15",
    "seconds": 4635,
    "pageStart": "",
    "pageEnd": "",
    "order": 1,
    "color": "#8b6fe8"
  },
  {
    "id": "工程數學-2",
    "subject": "工程數學",
    "name": "第01-2堂",
    "duration": "01:29:28",
    "seconds": 5368,
    "pageStart": "",
    "pageEnd": "",
    "order": 2,
    "color": "#8b6fe8"
  },
  {
    "id": "工程數學-3",
    "subject": "工程數學",
    "name": "第02-1堂",
    "duration": "01:26:49",
    "seconds": 5209,
    "pageStart": "",
    "pageEnd": "",
    "order": 3,
    "color": "#8b6fe8"
  },
  {
    "id": "工程數學-4",
    "subject": "工程數學",
    "name": "第02-2堂",
    "duration": "01:28:36",
    "seconds": 5316,
    "pageStart": "",
    "pageEnd": "",
    "order": 4,
    "color": "#8b6fe8"
  },
  {
    "id": "工程數學-5",
    "subject": "工程數學",
    "name": "第03-1堂",
    "duration": "01:28:40",
    "seconds": 5320,
    "pageStart": "",
    "pageEnd": "",
    "order": 5,
    "color": "#8b6fe8"
  },
  {
    "id": "工程數學-6",
    "subject": "工程數學",
    "name": "第03-2堂",
    "duration": "01:29:14",
    "seconds": 5354,
    "pageStart": "",
    "pageEnd": "",
    "order": 6,
    "color": "#8b6fe8"
  },
  {
    "id": "工程數學-7",
    "subject": "工程數學",
    "name": "第04-1堂",
    "duration": "01:30:07",
    "seconds": 5407,
    "pageStart": "",
    "pageEnd": "",
    "order": 7,
    "color": "#8b6fe8"
  },
  {
    "id": "工程數學-8",
    "subject": "工程數學",
    "name": "第04-2堂",
    "duration": "01:27:14",
    "seconds": 5234,
    "pageStart": "",
    "pageEnd": "",
    "order": 8,
    "color": "#8b6fe8"
  },
  {
    "id": "工程數學-9",
    "subject": "工程數學",
    "name": "第05-1堂",
    "duration": "01:29:18",
    "seconds": 5358,
    "pageStart": "",
    "pageEnd": "",
    "order": 9,
    "color": "#8b6fe8"
  },
  {
    "id": "工程數學-10",
    "subject": "工程數學",
    "name": "第05-2堂",
    "duration": "01:29:58",
    "seconds": 5398,
    "pageStart": "",
    "pageEnd": "",
    "order": 10,
    "color": "#8b6fe8"
  },
  {
    "id": "工程數學-11",
    "subject": "工程數學",
    "name": "第06-1堂",
    "duration": "01:30:31",
    "seconds": 5431,
    "pageStart": "",
    "pageEnd": "",
    "order": 11,
    "color": "#8b6fe8"
  },
  {
    "id": "工程數學-12",
    "subject": "工程數學",
    "name": "第06-2堂",
    "duration": "01:27:33",
    "seconds": 5253,
    "pageStart": "",
    "pageEnd": "",
    "order": 12,
    "color": "#8b6fe8"
  },
  {
    "id": "工程數學-13",
    "subject": "工程數學",
    "name": "第07-1堂",
    "duration": "01:31:12",
    "seconds": 5472,
    "pageStart": "",
    "pageEnd": "",
    "order": 13,
    "color": "#8b6fe8"
  },
  {
    "id": "工程數學-14",
    "subject": "工程數學",
    "name": "第07-2堂",
    "duration": "01:28:41",
    "seconds": 5321,
    "pageStart": "",
    "pageEnd": "",
    "order": 14,
    "color": "#8b6fe8"
  },
  {
    "id": "工程數學-15",
    "subject": "工程數學",
    "name": "第08-1堂",
    "duration": "01:24:59",
    "seconds": 5099,
    "pageStart": "",
    "pageEnd": "",
    "order": 15,
    "color": "#8b6fe8"
  },
  {
    "id": "工程數學-16",
    "subject": "工程數學",
    "name": "第08-2堂",
    "duration": "01:28:18",
    "seconds": 5298,
    "pageStart": "",
    "pageEnd": "",
    "order": 16,
    "color": "#8b6fe8"
  },
  {
    "id": "工程數學-17",
    "subject": "工程數學",
    "name": "第09-1堂",
    "duration": "01:29:21",
    "seconds": 5361,
    "pageStart": "",
    "pageEnd": "",
    "order": 17,
    "color": "#8b6fe8"
  },
  {
    "id": "工程數學-18",
    "subject": "工程數學",
    "name": "第09-2堂",
    "duration": "01:30:33",
    "seconds": 5433,
    "pageStart": "",
    "pageEnd": "",
    "order": 18,
    "color": "#8b6fe8"
  },
  {
    "id": "工程數學-19",
    "subject": "工程數學",
    "name": "第10-1堂",
    "duration": "01:31:43",
    "seconds": 5503,
    "pageStart": "",
    "pageEnd": "",
    "order": 19,
    "color": "#8b6fe8"
  },
  {
    "id": "工程數學-20",
    "subject": "工程數學",
    "name": "第10-2堂",
    "duration": "01:19:01",
    "seconds": 4741,
    "pageStart": "",
    "pageEnd": "",
    "order": 20,
    "color": "#8b6fe8"
  },
  {
    "id": "工程數學-21",
    "subject": "工程數學",
    "name": "第11-1堂",
    "duration": "01:29:21",
    "seconds": 5361,
    "pageStart": "",
    "pageEnd": "",
    "order": 21,
    "color": "#8b6fe8"
  },
  {
    "id": "工程數學-22",
    "subject": "工程數學",
    "name": "第11-2堂",
    "duration": "01:30:31",
    "seconds": 5431,
    "pageStart": "",
    "pageEnd": "",
    "order": 22,
    "color": "#8b6fe8"
  },
  {
    "id": "工程數學-23",
    "subject": "工程數學",
    "name": "第12-1堂",
    "duration": "01:31:11",
    "seconds": 5471,
    "pageStart": "",
    "pageEnd": "",
    "order": 23,
    "color": "#8b6fe8"
  },
  {
    "id": "工程數學-24",
    "subject": "工程數學",
    "name": "第12-2堂",
    "duration": "01:23:52",
    "seconds": 5032,
    "pageStart": "",
    "pageEnd": "",
    "order": 24,
    "color": "#8b6fe8"
  },
  {
    "id": "工程數學-25",
    "subject": "工程數學",
    "name": "第13-1堂",
    "duration": "01:26:19",
    "seconds": 5179,
    "pageStart": "",
    "pageEnd": "",
    "order": 25,
    "color": "#8b6fe8"
  },
  {
    "id": "工程數學-26",
    "subject": "工程數學",
    "name": "第13-2堂",
    "duration": "01:28:55",
    "seconds": 5335,
    "pageStart": "",
    "pageEnd": "",
    "order": 26,
    "color": "#8b6fe8"
  },
  {
    "id": "工程數學-27",
    "subject": "工程數學",
    "name": "第14-1堂",
    "duration": "01:27:35",
    "seconds": 5255,
    "pageStart": "",
    "pageEnd": "",
    "order": 27,
    "color": "#8b6fe8"
  },
  {
    "id": "工程數學-28",
    "subject": "工程數學",
    "name": "第14-2堂",
    "duration": "01:28:47",
    "seconds": 5327,
    "pageStart": "",
    "pageEnd": "",
    "order": 28,
    "color": "#8b6fe8"
  },
  {
    "id": "工程數學-29",
    "subject": "工程數學",
    "name": "第15-1堂",
    "duration": "01:27:55",
    "seconds": 5275,
    "pageStart": "",
    "pageEnd": "",
    "order": 29,
    "color": "#8b6fe8"
  },
  {
    "id": "工程數學-30",
    "subject": "工程數學",
    "name": "第15-2堂",
    "duration": "01:27:44",
    "seconds": 5264,
    "pageStart": "",
    "pageEnd": "",
    "order": 30,
    "color": "#8b6fe8"
  },
  {
    "id": "工程數學-31",
    "subject": "工程數學",
    "name": "第16-1堂",
    "duration": "01:24:21",
    "seconds": 5061,
    "pageStart": "",
    "pageEnd": "",
    "order": 31,
    "color": "#8b6fe8"
  },
  {
    "id": "工程數學-32",
    "subject": "工程數學",
    "name": "第16-2堂",
    "duration": "01:24:24",
    "seconds": 5064,
    "pageStart": "",
    "pageEnd": "",
    "order": 32,
    "color": "#8b6fe8"
  },
  {
    "id": "工程數學-33",
    "subject": "工程數學",
    "name": "第17-1堂",
    "duration": "01:29:38",
    "seconds": 5378,
    "pageStart": "",
    "pageEnd": "",
    "order": 33,
    "color": "#8b6fe8"
  },
  {
    "id": "工程數學-34",
    "subject": "工程數學",
    "name": "第17-2堂",
    "duration": "01:25:53",
    "seconds": 5153,
    "pageStart": "",
    "pageEnd": "",
    "order": 34,
    "color": "#8b6fe8"
  },
  {
    "id": "工程數學-35",
    "subject": "工程數學",
    "name": "第18-1堂",
    "duration": "01:24:55",
    "seconds": 5095,
    "pageStart": "",
    "pageEnd": "",
    "order": 35,
    "color": "#8b6fe8"
  },
  {
    "id": "工程數學-36",
    "subject": "工程數學",
    "name": "第18-2堂",
    "duration": "01:25:50",
    "seconds": 5150,
    "pageStart": "",
    "pageEnd": "",
    "order": 36,
    "color": "#8b6fe8"
  },
  {
    "id": "工程數學-37",
    "subject": "工程數學",
    "name": "第19-1堂",
    "duration": "01:24:53",
    "seconds": 5093,
    "pageStart": "",
    "pageEnd": "",
    "order": 37,
    "color": "#8b6fe8"
  },
  {
    "id": "工程數學-38",
    "subject": "工程數學",
    "name": "第19-2堂",
    "duration": "01:28:25",
    "seconds": 5305,
    "pageStart": "",
    "pageEnd": "",
    "order": 38,
    "color": "#8b6fe8"
  },
  {
    "id": "工程數學-39",
    "subject": "工程數學",
    "name": "第20-1堂",
    "duration": "01:25:41",
    "seconds": 5141,
    "pageStart": "",
    "pageEnd": "",
    "order": 39,
    "color": "#8b6fe8"
  },
  {
    "id": "工程數學-40",
    "subject": "工程數學",
    "name": "第20-2堂",
    "duration": "01:29:07",
    "seconds": 5347,
    "pageStart": "",
    "pageEnd": "",
    "order": 40,
    "color": "#8b6fe8"
  },
  {
    "id": "工程數學-41",
    "subject": "工程數學",
    "name": "第21-1堂",
    "duration": "01:28:12",
    "seconds": 5292,
    "pageStart": "",
    "pageEnd": "",
    "order": 41,
    "color": "#8b6fe8"
  },
  {
    "id": "工程數學-42",
    "subject": "工程數學",
    "name": "第21-2堂",
    "duration": "01:28:51",
    "seconds": 5331,
    "pageStart": "",
    "pageEnd": "",
    "order": 42,
    "color": "#8b6fe8"
  },
  {
    "id": "工程數學-43",
    "subject": "工程數學",
    "name": "第22-1堂",
    "duration": "01:26:26",
    "seconds": 5186,
    "pageStart": "",
    "pageEnd": "",
    "order": 43,
    "color": "#8b6fe8"
  },
  {
    "id": "工程數學-44",
    "subject": "工程數學",
    "name": "第22-2堂",
    "duration": "01:25:01",
    "seconds": 5101,
    "pageStart": "",
    "pageEnd": "",
    "order": 44,
    "color": "#8b6fe8"
  },
  {
    "id": "工程數學-45",
    "subject": "工程數學",
    "name": "第23-1堂",
    "duration": "01:30:10",
    "seconds": 5410,
    "pageStart": "",
    "pageEnd": "",
    "order": 45,
    "color": "#8b6fe8"
  },
  {
    "id": "工程數學-46",
    "subject": "工程數學",
    "name": "第23-2堂",
    "duration": "01:22:45",
    "seconds": 4965,
    "pageStart": "",
    "pageEnd": "",
    "order": 46,
    "color": "#8b6fe8"
  },
  {
    "id": "工程數學-47",
    "subject": "工程數學",
    "name": "第24-1堂",
    "duration": "01:25:11",
    "seconds": 5111,
    "pageStart": "",
    "pageEnd": "",
    "order": 47,
    "color": "#8b6fe8"
  },
  {
    "id": "工程數學-48",
    "subject": "工程數學",
    "name": "第24-2堂",
    "duration": "01:27:45",
    "seconds": 5265,
    "pageStart": "",
    "pageEnd": "",
    "order": 48,
    "color": "#8b6fe8"
  },
  {
    "id": "靜力學-1",
    "subject": "靜力學",
    "name": "第01-1堂",
    "duration": "02:25:21",
    "seconds": 8721,
    "pageStart": "",
    "pageEnd": "",
    "order": 1,
    "color": "#df9850"
  },
  {
    "id": "靜力學-2",
    "subject": "靜力學",
    "name": "第01-2堂",
    "duration": "00:45:35",
    "seconds": 2735,
    "pageStart": "",
    "pageEnd": "",
    "order": 2,
    "color": "#df9850"
  },
  {
    "id": "靜力學-3",
    "subject": "靜力學",
    "name": "第02-1堂",
    "duration": "01:55:46",
    "seconds": 6946,
    "pageStart": "",
    "pageEnd": "",
    "order": 3,
    "color": "#df9850"
  },
  {
    "id": "靜力學-4",
    "subject": "靜力學",
    "name": "第02-2堂",
    "duration": "01:22:00",
    "seconds": 4920,
    "pageStart": "",
    "pageEnd": "",
    "order": 4,
    "color": "#df9850"
  },
  {
    "id": "靜力學-5",
    "subject": "靜力學",
    "name": "第03-1堂",
    "duration": "01:28:38",
    "seconds": 5318,
    "pageStart": "",
    "pageEnd": "",
    "order": 5,
    "color": "#df9850"
  },
  {
    "id": "靜力學-6",
    "subject": "靜力學",
    "name": "第03-2堂",
    "duration": "01:11:26",
    "seconds": 4286,
    "pageStart": "",
    "pageEnd": "",
    "order": 6,
    "color": "#df9850"
  },
  {
    "id": "靜力學-7",
    "subject": "靜力學",
    "name": "第04-1堂",
    "duration": "02:05:57",
    "seconds": 7557,
    "pageStart": "",
    "pageEnd": "",
    "order": 7,
    "color": "#df9850"
  },
  {
    "id": "靜力學-8",
    "subject": "靜力學",
    "name": "第04-2堂",
    "duration": "01:15:13",
    "seconds": 4513,
    "pageStart": "",
    "pageEnd": "",
    "order": 8,
    "color": "#df9850"
  },
  {
    "id": "靜力學-9",
    "subject": "靜力學",
    "name": "第05-1堂",
    "duration": "02:03:03",
    "seconds": 7383,
    "pageStart": "",
    "pageEnd": "",
    "order": 9,
    "color": "#df9850"
  },
  {
    "id": "靜力學-10",
    "subject": "靜力學",
    "name": "第05-2堂",
    "duration": "01:30:31",
    "seconds": 5431,
    "pageStart": "",
    "pageEnd": "",
    "order": 10,
    "color": "#df9850"
  },
  {
    "id": "靜力學-11",
    "subject": "靜力學",
    "name": "第06-1堂",
    "duration": "02:12:06",
    "seconds": 7926,
    "pageStart": "",
    "pageEnd": "",
    "order": 11,
    "color": "#df9850"
  },
  {
    "id": "靜力學-12",
    "subject": "靜力學",
    "name": "第06-2堂",
    "duration": "01:07:48",
    "seconds": 4068,
    "pageStart": "",
    "pageEnd": "",
    "order": 12,
    "color": "#df9850"
  },
  {
    "id": "靜力學-13",
    "subject": "靜力學",
    "name": "第07-1堂",
    "duration": "02:05:13",
    "seconds": 7513,
    "pageStart": "",
    "pageEnd": "",
    "order": 13,
    "color": "#df9850"
  },
  {
    "id": "靜力學-14",
    "subject": "靜力學",
    "name": "第07-2堂",
    "duration": "01:29:52",
    "seconds": 5392,
    "pageStart": "",
    "pageEnd": "",
    "order": 14,
    "color": "#df9850"
  },
  {
    "id": "靜力學-15",
    "subject": "靜力學",
    "name": "第08-1堂",
    "duration": "02:02:23",
    "seconds": 7343,
    "pageStart": "",
    "pageEnd": "",
    "order": 15,
    "color": "#df9850"
  },
  {
    "id": "靜力學-16",
    "subject": "靜力學",
    "name": "第08-2堂",
    "duration": "01:20:49",
    "seconds": 4849,
    "pageStart": "",
    "pageEnd": "",
    "order": 16,
    "color": "#df9850"
  },
  {
    "id": "靜力學-17",
    "subject": "靜力學",
    "name": "第09-1堂",
    "duration": "02:02:59",
    "seconds": 7379,
    "pageStart": "",
    "pageEnd": "",
    "order": 17,
    "color": "#df9850"
  },
  {
    "id": "靜力學-18",
    "subject": "靜力學",
    "name": "第09-2堂",
    "duration": "01:09:21",
    "seconds": 4161,
    "pageStart": "",
    "pageEnd": "",
    "order": 18,
    "color": "#df9850"
  },
  {
    "id": "靜力學-19",
    "subject": "靜力學",
    "name": "第10-1堂",
    "duration": "02:18:19",
    "seconds": 8299,
    "pageStart": "",
    "pageEnd": "",
    "order": 19,
    "color": "#df9850"
  },
  {
    "id": "靜力學-20",
    "subject": "靜力學",
    "name": "第10-2堂",
    "duration": "01:17:37",
    "seconds": 4657,
    "pageStart": "",
    "pageEnd": "",
    "order": 20,
    "color": "#df9850"
  },
  {
    "id": "結構學-1",
    "subject": "結構學",
    "name": "第01-1堂",
    "duration": "01:44:16",
    "seconds": 6256,
    "pageStart": "",
    "pageEnd": "",
    "order": 1,
    "color": "#4c9a75"
  },
  {
    "id": "結構學-2",
    "subject": "結構學",
    "name": "第01-2堂",
    "duration": "01:34:07",
    "seconds": 5647,
    "pageStart": "",
    "pageEnd": "",
    "order": 2,
    "color": "#4c9a75"
  },
  {
    "id": "結構學-3",
    "subject": "結構學",
    "name": "第02-1堂",
    "duration": "02:04:56",
    "seconds": 7496,
    "pageStart": "",
    "pageEnd": "",
    "order": 3,
    "color": "#4c9a75"
  },
  {
    "id": "結構學-4",
    "subject": "結構學",
    "name": "第02-2堂",
    "duration": "01:05:28",
    "seconds": 3928,
    "pageStart": "",
    "pageEnd": "",
    "order": 4,
    "color": "#4c9a75"
  },
  {
    "id": "結構學-5",
    "subject": "結構學",
    "name": "第03-1堂",
    "duration": "01:48:55",
    "seconds": 6535,
    "pageStart": "",
    "pageEnd": "",
    "order": 5,
    "color": "#4c9a75"
  },
  {
    "id": "結構學-6",
    "subject": "結構學",
    "name": "第03-2堂",
    "duration": "01:13:59",
    "seconds": 4439,
    "pageStart": "",
    "pageEnd": "",
    "order": 6,
    "color": "#4c9a75"
  },
  {
    "id": "結構學-7",
    "subject": "結構學",
    "name": "第04-1堂",
    "duration": "01:53:59",
    "seconds": 6839,
    "pageStart": "",
    "pageEnd": "",
    "order": 7,
    "color": "#4c9a75"
  },
  {
    "id": "結構學-8",
    "subject": "結構學",
    "name": "第04-2堂",
    "duration": "01:15:31",
    "seconds": 4531,
    "pageStart": "",
    "pageEnd": "",
    "order": 8,
    "color": "#4c9a75"
  },
  {
    "id": "結構學-9",
    "subject": "結構學",
    "name": "第05-1堂",
    "duration": "02:13:14",
    "seconds": 7994,
    "pageStart": "",
    "pageEnd": "",
    "order": 9,
    "color": "#4c9a75"
  },
  {
    "id": "結構學-10",
    "subject": "結構學",
    "name": "第05-2堂",
    "duration": "00:52:57",
    "seconds": 3177,
    "pageStart": "",
    "pageEnd": "",
    "order": 10,
    "color": "#4c9a75"
  },
  {
    "id": "結構學-11",
    "subject": "結構學",
    "name": "第06-1堂",
    "duration": "01:59:11",
    "seconds": 7151,
    "pageStart": "",
    "pageEnd": "",
    "order": 11,
    "color": "#4c9a75"
  },
  {
    "id": "結構學-12",
    "subject": "結構學",
    "name": "第06-2堂",
    "duration": "01:17:14",
    "seconds": 4634,
    "pageStart": "",
    "pageEnd": "",
    "order": 12,
    "color": "#4c9a75"
  },
  {
    "id": "結構學-13",
    "subject": "結構學",
    "name": "第07-1堂",
    "duration": "02:11:02",
    "seconds": 7862,
    "pageStart": "",
    "pageEnd": "",
    "order": 13,
    "color": "#4c9a75"
  },
  {
    "id": "結構學-14",
    "subject": "結構學",
    "name": "第07-2堂",
    "duration": "00:55:10",
    "seconds": 3310,
    "pageStart": "",
    "pageEnd": "",
    "order": 14,
    "color": "#4c9a75"
  },
  {
    "id": "結構學-15",
    "subject": "結構學",
    "name": "第08-1堂",
    "duration": "02:04:02",
    "seconds": 7442,
    "pageStart": "",
    "pageEnd": "",
    "order": 15,
    "color": "#4c9a75"
  },
  {
    "id": "結構學-16",
    "subject": "結構學",
    "name": "第08-2堂",
    "duration": "01:02:56",
    "seconds": 3776,
    "pageStart": "",
    "pageEnd": "",
    "order": 16,
    "color": "#4c9a75"
  },
  {
    "id": "結構學-17",
    "subject": "結構學",
    "name": "第09-1堂",
    "duration": "01:57:30",
    "seconds": 7050,
    "pageStart": "",
    "pageEnd": "",
    "order": 17,
    "color": "#4c9a75"
  },
  {
    "id": "結構學-18",
    "subject": "結構學",
    "name": "第09-2堂",
    "duration": "01:06:00",
    "seconds": 3960,
    "pageStart": "",
    "pageEnd": "",
    "order": 18,
    "color": "#4c9a75"
  },
  {
    "id": "結構學-19",
    "subject": "結構學",
    "name": "第10-1堂",
    "duration": "01:56:37",
    "seconds": 6997,
    "pageStart": "",
    "pageEnd": "",
    "order": 19,
    "color": "#4c9a75"
  },
  {
    "id": "結構學-20",
    "subject": "結構學",
    "name": "第10-2堂",
    "duration": "01:15:44",
    "seconds": 4544,
    "pageStart": "",
    "pageEnd": "",
    "order": 20,
    "color": "#4c9a75"
  },
  {
    "id": "結構學-21",
    "subject": "結構學",
    "name": "第11-1堂",
    "duration": "01:55:45",
    "seconds": 6945,
    "pageStart": "",
    "pageEnd": "",
    "order": 21,
    "color": "#4c9a75"
  },
  {
    "id": "結構學-22",
    "subject": "結構學",
    "name": "第11-2堂",
    "duration": "01:20:59",
    "seconds": 4859,
    "pageStart": "",
    "pageEnd": "",
    "order": 22,
    "color": "#4c9a75"
  },
  {
    "id": "結構學-23",
    "subject": "結構學",
    "name": "第12-1堂",
    "duration": "02:12:06",
    "seconds": 7926,
    "pageStart": "",
    "pageEnd": "",
    "order": 23,
    "color": "#4c9a75"
  },
  {
    "id": "結構學-24",
    "subject": "結構學",
    "name": "第12-2堂",
    "duration": "01:03:14",
    "seconds": 3794,
    "pageStart": "",
    "pageEnd": "",
    "order": 24,
    "color": "#4c9a75"
  },
  {
    "id": "結構學-25",
    "subject": "結構學",
    "name": "第13-1堂",
    "duration": "02:02:51",
    "seconds": 7371,
    "pageStart": "",
    "pageEnd": "",
    "order": 25,
    "color": "#4c9a75"
  },
  {
    "id": "結構學-26",
    "subject": "結構學",
    "name": "第13-2堂",
    "duration": "01:14:55",
    "seconds": 4495,
    "pageStart": "",
    "pageEnd": "",
    "order": 26,
    "color": "#4c9a75"
  }
];